name: D/Y
url: http://do6year.github.io
description: Personal blog with my passion in programming.

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
